theme: jekyll-theme-leap-day
title: 見習いエンジニアの備忘録
description: 電機メーカー6年目のエンジニアです。私を始めとする見習い〜中堅エンジニアのための参考資料や経験のまとめ場&共にスキルアップしていきたいという思いから当サイトを立ち上げました。Quittaをはじめとした技術録に助けられる毎日から、私も誰かのために恩返ししたいというモチベーションで始めました。宜しくお願いします。